# Generated by Django 3.2.12 on 2024-02-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='amenities',
            field=models.ManyToManyField(related_name='rooms', to='website.Amenity'),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='amenity',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Check In', 'Check In'), ('Check Out', 'Check Out'), ('In Progress', 'In Progress')], default='Check In', max_length=50),
        ),
    ]
