# Generated by Django 3.2.12 on 2024-02-13 13:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial '),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='surname',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='userImg',
            field=models.URLField(default=django.utils.timezone.now, verbose_name='userImg'),
            preserve_default=False,
        ),
    ]
