# Generated by Django 3.2.12 on 2024-02-13 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20240213_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='userImg',
        ),
    ]
