# Generated by Django 3.2.12 on 2024-02-09 15:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20240209_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(default='diego@diegomompo.com', max_length=255, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(code='invalid_registration', message='Enter a valid format phone number', regex='^(0|91)?[6-9][0-9]{8}')]),
        ),
    ]
