# Generated by Django 3.2.12 on 2024-02-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20240209_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='Email'),
        ),
    ]
