# Generated by Django 3.2.12 on 2024-02-14 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20240213_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateField(default=datetime.date(2024, 2, 14)),
        ),
        migrations.AlterField(
            model_name='order',
            name='timestamps',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
