# Generated by Django 3.2.12 on 2024-02-12 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_contact_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='userImg',
        ),
    ]
