# Generated by Django 3.2.12 on 2024-02-14 10:45

import datetime
from django.db import migrations, models
import datetime
from django.conf import settings
import django.core.validators
import django.db.models.deletion
import website.models.Booking


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20240213_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Food', 'Food'), ('Other', 'Other')], max_length=10)),
                ('description', models.TextField(max_length=255)),
                ('timestamps', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
