# Generated by Django 3.2.12 on 2024-02-12 10:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_contact_userimg'),
    ]

    operations = [
    
    ]
