# Generated by Django 3.2.12 on 2024-02-12 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_contact_userimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='surname',
            new_name='fullName',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
    ]
