# Generated by Django 3.2.12 on 2024-02-14 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20240214_1045 copy'),
        ('website', '0006_auto_20240214_1045'),
    ]

    operations = [
    ]
