# Generated by Django 3.2.12 on 2024-03-19 17:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_merge_20240214_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='specialRequest',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateField(default=datetime.date(2024, 3, 19)),
        ),
        migrations.AddField(
            model_name='amenity',
            name='image',
            field=models.CharField(max_length=500),  # Definición del campo CharField
            preserve_default=False,  # Opcional, según sea necesario
        ),
    ]
