# Generated by Django 3.2.12 on 2024-02-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20240212_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='fullName',
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
    ]
