# Generated by Django 3.2.12 on 2024-03-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20240319_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='image',
            field=models.CharField(max_length=500),  # Definición del campo CharField
            preserve_default=False,  # Opcional, según sea necesario
        ),
    ]
