# Generated by Django 3.2.12 on 2024-02-12 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_contact_fullname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='surname',
        ),
    ]
