# Generated by Django 3.2.12 on 2024-03-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_remove_amenity_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='image',
            field=models.CharField(max_length=5000),  # Definición del campo CharField
        ),
    ]
