# Generated by Django 3.2.12 on 2024-02-12 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20240212_1102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['fullName', 'email']},
        ),
    ]
