# Generated by Django 3.2.12 on 2024-02-07 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_alter_booking_check_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='job',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Receptionist', 'Receptionist'), ('Room Service', 'Room Service')], max_length=100),
        ),
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amenity', models.CharField(max_length=1000)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.room')),
            ],
        ),
    ]
